# Generated by Django 2.0 on 2018-02-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeformacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeformacao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeformacao',
            name='num_participantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeformacao',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centromemoria',
            name='num_titulos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='num_participantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervencaopolitica',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervencaopolitica',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
